name: xkcd
options:
  minimumXcodeGenVersion: 2.5.0
  bundleIdPrefix: com.codecritique
targets:
  xkcd:
    type: application
    platform: iOS
    sources:
      - sources
      - assets
  xkcdTests:
    type:  bundle.unit-test
    platform: iOS
    sources:
        - xkcdTests
    dependencies:
      - target: xkcd
    scheme:
      testTargets:
        - xkcdTests
    postbuildScripts:
      - path: scripts/swiftlint.sh
        name: SwiftLint
      - path: scripts/xcodeFormating.sh
        name: XcodeFormating
