name: xkcd
options:
  minimumXcodeGenVersion: 2.5.0
  bundleIdPrefix: com.codecritique
targets:
  xkcd:
    type: application
    platform: iOS
    sources:
      - sources
      - assets

    postbuildScripts:
      - path: scripts/swiftlint.sh
        name: SwiftLint
      - path: scripts/xcodeFormating.sh
        name: XcodeFormating
