name: xkcd
options:
  minimumXcodeGenVersion: 2.5.0
  bundleIdPrefix: com.codecritique
targets:
  Tests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - tests
    dependencies:
      - target: xkcd
    scheme:
      testTargets:
        - Tests
  xkcd:
    type: application
    platform: iOS
    sources:
      - sources
      - assets
    postbuildScripts:
      - path: scripts/swiftlint.sh
        name: SwiftLint
      - path: scripts/xcodeFormating.sh
        name: XcodeFormating
